---
author:
  - name: Stuart Lee
    affiliation: Monash University
    # use this syntax to add text on several lines
    address: |
      | Department of Econometrics and Business Statistics,
      | Monash University
    email: stuart.a.lee@monash.edu
  - name: Ursula Laa 
    affiliation: University of Natural Resources and Life Sciences
    address:  |
      | Institute of Statistics,
      | University of Natural Resources and Life Sciences
    email:  ursula.laa@boku.ac.at
  - name: Natalia da Silva
    address: |
      | Instituto de Estadística (IESTA), 
      | Universidad de la República
    affiliation: Universidad de la República
    email: natalia@iesta.edu.uy
  - name: Nicholas Spyrison
    address: |
      | Faculty of Information and Technology 
      | Monash University
    affiliation: Monash University
    email: nicholas.spyrison@monash.edu
  - name: Dianne Cook
    address: |
      | Department of Econometrics and Business Statistics,
      | Monash University
    affiliation: Monash University
    email: dicook@monash.edu
  - name: Earo Wang
    address: |
      | Department of Statistics,
      | The University of Auckland
    affiliation: The University of Auckland
    email: earo.wang@auckland.ac.nz
  - name: H. Sherry Zhang
    address: |
      | Department of Econometrics and Business Statistics,
      | Monash University
    affiliation: Monash University
    email: huize.zhang@monash.edu
title:
  formatted: "An Overview of Tours for Dynamic Visualisation of High-dimensional Data"
abstract: > 
  Abstract goes here.
keywords:
  formatted: ["tours", "data visualisation"]
output: 
  bookdown::pdf_document2:
    template: template/wires_template_rmd.tex
    keep_tex: true
    toc: false
bibliography: references.bib
biblio-style: apalike
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  fig.show = 'hold',
  dpi = 300 #,
  # out.width = "\\textwidth",
  # fig.path = here::here('img/')
)
```

<!--
Writing style: third person (it was done, ...)
-->

# Introduction

<!-- Purpose/why and what is high-d data (Di)-->

Data commonly arrives with more than two measured variables, which makes it more complicated to plot on a page. With multiple variables, especially if there is some association between variables, this would be called multivariate or high-dimensional data. When the variables are all numeric, or quantitative, visualisation often relies on some form of dimension reduction. This can be done by taking linear projections, for example, principal component analysis [@Hotelling1933-of] or linear discriminant analysis [@Fisher1936]. It is also common to reduce dimension nonlinearly with techniques like multidimensional scaling (MDS) [@Kruskal1964-do] or t-Distributed Stochastic Neighbour Embedding (t-SNE) [@Van_der_Maaten2008-qa]. 

The focus of this review will be on linear projections, in particular, as provided by the grand tour [@Asimov1985-xr; @Buja2005-cx]. The reason being that it is not feasible to adequately the very large area of visualising high-dimensions, and there have been numerous developments in tours recently.  An overview of the technique, and new modifications is provided, along with how these techniques can be used in a variety of applications, and to help understand nonlinear dimension reduction results.  

A tour can be considered to be a dynamic graphic, because it shows a smooth sequence of projections over time, ideally with controls that allow stopping, reversing, changing direction, or going forward again. It can be useful to embed a tour into an interactive graphics system, where plots can be queried and elements highlighted (see for e.g. @Swayne2003-cc or @Tierney1991). To create the smooth sequence, a geodesic interpolation is computed between consecutive frames.  It allows the viewer to extrapolate from the low-dimensional to  shapes corresponding to multivariate distribution, and is particularly useful for detecting clusters, outliers and non-linear dependence. 

> figure 1 illustrating tour views vs nonlinear dimension reduction for Stuart's cluster example

While tours are invaluable for assessing the geometry of data, they are by no means the only technique available for visualising structure in high dimensional data. An early technique proposed for assessing pairwise relationships between variables is the scatter plot matrix (SPLOM) [@Tukey1983-fj] <!-- there might be others here(?) -->. In this graphic, the canvas is split into a matrix where each off-diagonal element is a scatter plot of variable pairs, while the diagonal elements are either left blank or represent univariate structure. The SPLOM allows the viewer to assess correlation structure but does not scale to large numbers of variables. 

Similarly, parallel coordinates plots (PCP) can be used to explore correlation and co-linearities in multivariate data [@Inselberg1985-kf]. In PCPs, variables are arranged along the (vertical) horizontal axis with vertical (horizontal) axes drawn representing the range of values for each variable. Points (observations) of the data are represented by drawing lines between each variables axis. If there is positive correlation between two variables the lines will be parallel, while for negative correlation the lines will cross. By placing multiple variables side by side in a PCP higher order structure like clustering or lower dimensional embeddings is revealed, however the ordering of variables is important to reveal these features. <!-- anything else? Andrew's curves etc., heat? -->

<!-- Original tours (Di)
- Dataviewer, XGobi, GGobi, cranvas (XLispStat, Orca, mmvz) (Di)
(picture of the cluster data from Stuart's thesis)
- Alternatives (Stuart) 
  - cluster heatmaps 
  - data pipelines (?)
  - point to other reviews
- What do we mean by multivariate data visualisation?
- multivariate categorical vis, tree maps etc.
- subplots trellis literature
-->


# Tours for high dimensional visualization 

- Bases notation (Sherry)

Some notations are defined for describing $d$-dimensional projections in $p$-dimensional space. Let $X_{n \times p}$ be the original data whose projections are of our interest. A projection basis, $A_{p \times d}$, characterises the direction from which the high-dimensional data are projected. A constraint that projection bases needs to satisfy is the orthonormality condition (which requires each axis to be unit vector and perpendicular to each other). This gives the basis space a geometrical structure of a Stiefel manifold. The projection of the original data on a basis hence can be defined as $Y = X \cdot A$. The projection is usually in 1D or 2D for the purpose of visual display. 

> figure 2 diagram illustrating a projection

- Display (Sherry)

[@Wickham2011-uz]

1D: `display_hist`: histogram
2D: `display_xy`, recent development `display_sage()` - will be detailed in the last section Transformations on projections (Ursula)

> figure 3 diagram illustrating different displays for different d

- Choosing targets, inc pp indexes (Sherry)

grand tour, random, may miss interesting, take long to rotate to that specific angle, guided tour, along with projection pursuit, by generating target bases, interestingness

interesting, index function, $f: \mathbb{R}^{n \times d} \mapsto \mathbb{R}$, normality, theoretical result: [@Diaconis1984-mv], aslo peter huber projection pursuit

index: 
  - initial idea from Friedman, orthonormal function expansion (Do we need to review these old index contruction?)
  - holes, central mass, PDA, LDA
  - scagnostic indices
  - skewness & kurtosis index loperfido (moment)
  - chi-square @posse for detect spiral

> figure 4 diagram illustrating different types of target generation

- Geodesic interpolation (Ursula)

> figure 5 diagram illustrating geodesic interpolation

- Slices vs projections (Ursula)

> figure 6 diagram illustrating projection vs slice

- Transformations on projections (Ursula)

> figure 7 diagram of burning sage transformation

# Ways of interacting

- Stop/start/reverse

> pull something from ggobi book?
> figure 8 illustration

- Manual (Nick)

> something from nick's paper
> figure 9 illustration

- Linked brushing (Earo)

> something from ggobi book
> > figure 10: plots showing example

- Spin-and-brush  (Ursula)
    
> something from ggobi book
> figure 11: plots showing example

# Software

- tourr (Di) 
- spinifex (Nick)

The R package spinifex [@spyrison_spinifex_2020] has 3 primary features: it produces manual tours (predefined path or interactive manipulation, identifies orthonormal global feature bases with the use of the Rdimtools [@you_rdimtools_2020] package, renders (manual or other) tours as animations exportable to static .gif or interactive .html widgets, lastly it offers interactive shiny application that offers an graphical user interface to quickly sample tour features.

- liminal (Stuart)

The liminal R package uses the tour to explore the quality of non-linear dimensionality reduction algorithms. The interface consists of two side by side views consisting of a scatter plot displaying a reduced form of the data, and an interactive tour. Controls such as play/stop/restart are implemented allowing a user to pause on interesting projections and return them to their R session for further analysis. Linked brushing is implemented on both views - if a users brush on the scatter plot view they can see if and how an algorithm like t-SNE has distorted distances in higher dimensional space, while if they brush on the tour view, the tour is paused and structure like cluster separation can be ascertained.      


- python (Di to follow up with Csaba)

# Application

- Model vis examples eg random forest (from Hadley, removing the blindfold) (Natalia)

> figure 12 tour plot(s) of vote matrix and tour plot(s) of variables, with some annotation of cases?

- Physics (Ursula)

> figure 13 

- Bioinformatics (Stuart)

In single cell RNA sequencing, scientists are interested in identifying novel cell types and understanding the relationships between cells or their developmental trajectory. To achieve this they perform cluster analysis on a counts matrix or principal components and embed the results via t-SNE and label points according the cluster label. One of the main advantages of t-SNE is the avoidance of over-plotting so clusters can be clearly identified on a scatter plot, however, this can come at the cost of interpretability as global distances are distorted.  In @Laa2020-uv, we used radial transformations of the tour projections as an alternative to t-SNE that better preserves global structure while still retaining cluster topology.

> figure 14

- High-d shapes/distributions: normal, skewed, outliers, (Di from tutorial notes)

> figure 15

- neural networks (from Scheidegger - Stuart)

> figure 16

- umap (Mingwei Li paper - Stuart)

> figure 17

# Discussion

# References {-}
